service: lambda-notifier

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 1 

functions:
  notifier:
    handler: handler.notifier
    description: Lambda responsável em enviar notificações no telegram, usando o SNS como trigger
    events:
      - sns: ${SNS}


